[package]
name = "configurator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
common = { version = "0.1.0", path = "../common" }
dialoguer.workspace = true
serde.workspace = true
toml.workspace = true
chrono.workspace = true